### ISSUE TITLE
Problems after installation

### ISSUE THREAD

**Issue by oggito** [stephane-/gantt_improvement#7]
Hi,

First of all I have downloaded the zip file. Then I have imported the module to my instance, afterwards it gets installed, I logout and then login into the odoo and 2 error messages do appear on the top of the screen. I attach a screenshot.

Please let me know how to fix that.

Thank you.
![screen shot 2014-12-19 at 16 43 32](https://cloud.githubusercontent.com/assets/10244838/5506896/96b748d0-879e-11e4-834d-113c8754dc75.png)

**Comment by Hopiu** [comment]
I solved the "could not get content problem" by renaming the addon's folder from gantt_improvement-master/ to gantt_improvement/. Anyway I can't notice any changes to the gantt charts too. Do I have to uninstall the "Web Gantt" module?

**Comment by oggito** [comment]
I followed the last instructions with changing the name of the directory.

The problem is, that after I have installed the module, I cannot select any option from the menu in odoo, nothing is loading and I have a huge problem, because I need to restore the system.

I am running it on ubuntu.

Any help will be appreciated of how to remove the module or its directory, so I can at least run my instance!

Thank you. It is urgent.

**Comment by oggito** [comment]
Any idea of the name of the installation folder of the gantt improvement module?

I need to find it on the ubuntu server and remove it from there. Otherwise I am really in a terrible situation with a not running system.

**Comment by Hopiu** [comment]
D you have access to the server?
Try the command `find / -name "Odoo"` to locate the Odoo installation folder. There's an addon folder in it and depending on your installation a folder `8.0` in which I installed `gantt_improvement`

**Comment by stephane-** [comment]
Hello,
I'm sorry for the response time.

If you still have the problem, you can rename your module for "grantt_improvement_master" uninstall with admin panel and rename it "grantt_improvement" and reinstall it.

If you change the directory name at the same time it is installed, Odoo can not uninstall it.
