### ISSUE TITLE
Gantt error

### ISSUE THREAD

**Issue by anhdv1979** [stephane-/gantt_improvement#8]
Many thanks for your gantt_improvement. When using it, I find something wrong.
1. If work order with working time e.g from monday to saturday, 8:00 to 16:00, this leads error in calculating the time of work order 's display.
2. When resizing time of work order, sometimes it causes errors
![1](https://cloud.githubusercontent.com/assets/7521909/8843268/a3c341aa-3130-11e5-8877-c0fc111679bb.png)

3. Not showing tooltip the estimated time of work order bar

Pls help me check. Thanks alot

**Comment by stephane-** [comment]
Hello, 
I push a new version in dev branch.
I update the dhtmlx version, and I re-code lot of functions of my module.
For moment task resizing are blocked.

For you'r first point, I don't understand what's your case. 
Do you have a multi task ? Can you tell me an module use this feature ?

Thank for your comment,
Stéphane

**Comment by stephane-** [comment]
In the absence of feedback, I close this issue.
If you encounter other problems please feel free to create a new issue.
